version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    container_name: med-adn-backend
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`med-adn.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

networks:
  dokploy-network:
    external: true
